spelling correction - README.MD
should be NATO instead of nato, otherwise get error
ERROR:  Could not find a valid gem 'nato' (>= 0) in any repository
ERROR:  Possible alternatives: NATO